### ISSUE TITLE
reducer里面这句不是很懂

### ISSUE THREAD

**Issue by Hanck97** [chenjun1127/react-music#2]
// 去除数组里的重复对象
            let newArr = arr.reduce((item, next) => {
                hash[next.song.hash] ? '' : hash[next.song.hash] = true && item.push(next);
                return item
            }, []);
能稍微讲讲嘛 感谢

**Comment by chenjun1127** [comment]
去看看数组的reduce用法
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce?v=a

**Comment by ziveen** [comment]
异步请求放在action里面不是更好?component傻瓜组件,应该不做交互之类的
