### ISSUE TITLE
无法打包欸

### ISSUE THREAD

**Issue by Hanck97** [chenjun1127/react-music#3]
npm run build后 报 'rimraf' 不是内部或外部命令，也不是可运行的程序或批处理文件。

**Comment by chenjun1127** [comment]
无法打包是正常情况，想发布上线必须使用正规API接口，这里只是作开发用，API用的代理

**Comment by HancockTong** [comment]
![fireshot capture 1 - react-music - http___localhost_3000_artist](https://user-images.githubusercontent.com/25978112/34280189-0dc9c06a-e6f1-11e7-84c3-a2efec266668.png)
导航栏首页字的位置还是正常的，点击到其他页面就会变了
